// Generated by CoffeeScript 1.6.3
(function() {
  var $;
  $ = jQuery;
  
  $(document).ready(function() {
    $('.ui-icon-hand').css('margin-left', '-=200px');
    $('blockquote').css({
      left: '0px',
      opacity: 1
    });
    $('.section').each(function() {
      return $(this).onScreen({
        doIn: function() {
          $(this).find('h2,p').css({
            left: 0,
            opacity: 1
          });
          $(this).find('.focus-img').css('-webkit-transform', 'scale(1, 1)').css('-moz-transform', 'scale(1, 1)').css('-ms-transform', 'scale(1, 1)').css('-o-transform', 'scale(1, 1)').css('transform', 'scale(1, 1)');
          return $(this).find('.ui-icon, .contact-link').css({
            top: 0,
            opacity: 1
          });
        }
      });
    });
  });

}).call(this);
